import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ResponsiveAppBar from "@/components/AppBar";
import AppFooter from "@/components/AppFooter";
import MuiTheme from "@/styles/MuiTheme";
import { Provider } from "@/redux/providers";
import { MantineProvider, createTheme } from "@mantine/core";
import { ThemeProvider } from "@mui/material/styles";

const inter = Inter({ subsets: ["latin"] });
const theme = createTheme({
  /** Put your mantine theme override here */
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <MantineProvider theme={theme}>
            <MuiTheme>
              <div className="flex flex-col min-h-screen">
                <ResponsiveAppBar></ResponsiveAppBar>
                {children}
                <AppFooter></AppFooter>
              </div>
            </MuiTheme>
          </MantineProvider>
        </Provider>
      </body>
    </html>
  );
}
